### ISSUE TITLE
Update Instructions

### ISSUE THREAD

**Issue by louislongin** [The-E/GinUI#17]
Hello The-E!
 
I am working for G-Node and I am trying to get the GinUI client to run. 
However, I am having troubles with the installation as I cannot get the Gin Login screen to appear. Everything works until step 8. However, step 9 is for me impossible to reach. 

It might be linked to a missing certificate installation as I cannot build the GinShellExtension. Additionally, when attemping to install the certificates GinShellExtension.pfx, it requires a for me unknown password.

Maybe you can help me/us out? Thank you!

**Comment by The-E** [comment]
The password has been removed from the signing key.
